services:
  web:
    build: .
    command: uvicorn server.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"